# mkdocs.yml
site_name: Todo App Documentation
site_description: Documentation for the Todo Application
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
            show_root_heading: true

nav:
  - Home: index.md
  - Getting Started:
    - Setup: setup.md
    - Testing:
      - Overview: testing.md
      - Detailed Guide: testing-extended.md
  - Reference:
    - API Documentation: api.md
    - Database Schema: database.md
  - Help:
    - Troubleshooting: troubleshooting.md
    - Contributing: contributing.md