name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to EC2
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          # Cambiar al directorio donde se desplegará la app
          cd ~/app_to_do_list || mkdir ~/app_to_do_list && cd ~/app_to_do_list

          if [ ! -d ".git" ]; then
            git clone https://github.com/brissporras26/app_to_do_list.git .
          else
            git pull origin main
          fi

          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

          export $(cat .env | xargs)

          nohup python run.py > app.log 2>&1 & EOF
